# Generated by Django 3.0.2 on 2020-03-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('Node_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Node_Name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='M_to_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_id', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='CareerGuidance.Job')),
                ('Node_id', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='CareerGuidance.Node')),
            ],
        ),
    ]
