# Generated by Django 3.0.2 on 2020-03-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0002_m_to_m_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('Skill_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Skill_Name', models.CharField(default='', max_length=50)),
                ('Job_id', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='CareerGuidance.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('Tool_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Tool_Name', models.CharField(default='', max_length=1000)),
                ('Skill_id', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='CareerGuidance.Skillset')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('Resource_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Resource_Link', models.CharField(default='', max_length=1000)),
                ('Skill_id', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='CareerGuidance.Skillset')),
            ],
        ),
    ]
