# Generated by Django 3.0.2 on 2020-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0003_resource_skillset_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='cons',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='node',
            name='pros',
            field=models.CharField(default='', max_length=300),
        ),
    ]
