# Generated by Django 2.2.8 on 2020-03-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerGuidance', '0005_aptitude_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude_test',
            name='Question',
            field=models.CharField(default='null', max_length=100222),
        ),
    ]
